name: Test whereis
on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      - run: npm install

      - name: Create idoc config.
        run: |
          cat > idoc.yml << EOF
          site: "whereis"
          description: Like the unix `which` utility.
          keywords: whereis,which,bin,path,unix,cli,command,command-line,utility
          openSource: https://github.com/jaywcjlove/whereis
          homepage: https://wangchujiang.com/whereis/
          tocs: false
          element: 
            wrapper: style=max-width:720px;
          meta:
            - <meta name="author" content="Kenny Wong">
            - <meta property="og:site_name" content="<%= site %>">
            - <meta property="og:url" content="<%=homepage%><%=RESOLVE_PATH%>">
            - <meta property="og:type" content="website">
            - <meta property="og:title" content="<%= site %> - <%= description%>">
            - <meta property="og:description" content="<%= description%>">
          menus:
            Home: index.html
            Apps: 
              url: https://wangchujiang.com/#/app
              target: __blank
            Sponsor: 
              url: https://jaywcjlove.github.io/#/sponsor
              target: __blank
          footer: |
            <a href="https://wangchujiang.com/#/app" target="_blank">App</a> • 
            <a href="https://wangchujiang.com/#/projects" target="_blank">Projects</a> • 
            <a href="https://wangchujiang.com/#/sponsor" target="_blank">Sponsor</a> • 
            <a href="https://wangchujiang.com/#/app" target="_blank">More Apps</a><br /><br />
            Generated by <a href="https://github.com/jaywcjlove/idoc" target="_blank">idoc</a> v{{idocVersion}}      
          EOF

      - run: npm run build
      - run: npm run tsc
      - run: npm run test
      - run: npm run coverage

      - run: cp -rp coverage dist

      - name: Create Coverage Badges
        uses: jaywcjlove/coverage-badges-cli@main
        with:
          source: coverage/coverage-summary.json
          output: dist/badges.svg

      - name: Generate Contributors Images
        uses: jaywcjlove/github-action-contributors@main
        with:
          filter-author: (renovate\[bot\]|renovate-bot|dependabot\[bot\])
          output: dist/CONTRIBUTORS.svg
          avatarSize: 42

      - name: Create Tag
        id: create_tag
        uses: jaywcjlove/create-tag-action@main
        with:
          package-path: ./package.json

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          user_name: github-actions[bot]
          user_email: github-actions[bot]@users.noreply.github.com
      
      - name: Generate changelog
        id: changelog
        uses: jaywcjlove/changelog-generator@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filter-author: (jaywcjlove|小弟调调™|dependabot|renovate\\[bot\\]|dependabot\\[bot\\]|Renovate Bot)
          filter: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'

      - name: Create Release
        uses: ncipollo/release-action@v1
        if: steps.create_tag.outputs.successful
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ steps.create_tag.outputs.version }}
          tag: ${{ steps.create_tag.outputs.version }}
          body: |
            [![Buy me a coffee](https://img.shields.io/badge/Buy%20me%20a%20coffee-048754?logo=buymeacoffee)](https://jaywcjlove.github.io/#/sponsor) [![](https://img.shields.io/badge/Open%20in-unpkg-blue)](https://uiwjs.github.io/npm-unpkg/#/pkg/@wcjiang/whereis@${{steps.changelog.outputs.version}}/file/README.md)
            
            Documentation ${{ steps.changelog.outputs.tag }}: https://raw.githack.com/jaywcjlove/whereis/${{ steps.changelog.outputs.gh-pages-short-hash }}/index.html  
            Comparing Changes: ${{ steps.changelog.outputs.compareurl }}  

            ```shell
            npm i @wcjiang/whereis@${{steps.create_tag.outputs.versionNumber}}
            ```

            ${{ steps.changelog.outputs.changelog }}

      - name: 📦 @wcjiang/whereis publish to NPM
        run: npm publish --access public --provenance
        continue-on-error: true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}